/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/authenticated'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAboutRouteImport } from './routes/authenticated.about'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/authenticated.audit-log'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/authenticated.categories'
import { Route as AuthenticatedDashboardRouteImport } from './routes/authenticated.dashboard'
import { Route as AuthenticatedExportsRouteImport } from './routes/authenticated.exports'
import { Route as AuthenticatedReportsRouteImport } from './routes/authenticated.reports'
import { Route as AuthenticatedRulesRouteImport } from './routes/authenticated.rules'
import { Route as AuthenticatedSettingsRouteImport } from './routes/authenticated.settings'
import { Route as AuthenticatedStatementsRouteImport } from './routes/authenticated.statements'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/authenticated.templates'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/authenticated.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportsRoute = AuthenticatedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatementsRoute = AuthenticatedStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authenticated/about': typeof AuthenticatedAboutRoute
  '/authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/exports': typeof AuthenticatedExportsRoute
  '/authenticated/reports': typeof AuthenticatedReportsRoute
  '/authenticated/rules': typeof AuthenticatedRulesRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRoute
  '/authenticated/statements': typeof AuthenticatedStatementsRoute
  '/authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/authenticated/transactions': typeof AuthenticatedTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authenticated/about': typeof AuthenticatedAboutRoute
  '/authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/exports': typeof AuthenticatedExportsRoute
  '/authenticated/reports': typeof AuthenticatedReportsRoute
  '/authenticated/rules': typeof AuthenticatedRulesRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRoute
  '/authenticated/statements': typeof AuthenticatedStatementsRoute
  '/authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/authenticated/transactions': typeof AuthenticatedTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authenticated/about': typeof AuthenticatedAboutRoute
  '/authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/exports': typeof AuthenticatedExportsRoute
  '/authenticated/reports': typeof AuthenticatedReportsRoute
  '/authenticated/rules': typeof AuthenticatedRulesRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRoute
  '/authenticated/statements': typeof AuthenticatedStatementsRoute
  '/authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/authenticated/transactions': typeof AuthenticatedTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/authenticated'
    | '/reset-password'
    | '/auth/callback'
    | '/authenticated/about'
    | '/authenticated/audit-log'
    | '/authenticated/categories'
    | '/authenticated/dashboard'
    | '/authenticated/exports'
    | '/authenticated/reports'
    | '/authenticated/rules'
    | '/authenticated/settings'
    | '/authenticated/statements'
    | '/authenticated/templates'
    | '/authenticated/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/authenticated'
    | '/reset-password'
    | '/auth/callback'
    | '/authenticated/about'
    | '/authenticated/audit-log'
    | '/authenticated/categories'
    | '/authenticated/dashboard'
    | '/authenticated/exports'
    | '/authenticated/reports'
    | '/authenticated/rules'
    | '/authenticated/settings'
    | '/authenticated/statements'
    | '/authenticated/templates'
    | '/authenticated/transactions'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/authenticated'
    | '/reset-password'
    | '/auth/callback'
    | '/authenticated/about'
    | '/authenticated/audit-log'
    | '/authenticated/categories'
    | '/authenticated/dashboard'
    | '/authenticated/exports'
    | '/authenticated/reports'
    | '/authenticated/rules'
    | '/authenticated/settings'
    | '/authenticated/statements'
    | '/authenticated/templates'
    | '/authenticated/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/authenticated/about': {
      id: '/authenticated/about'
      path: '/about'
      fullPath: '/authenticated/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/audit-log': {
      id: '/authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/authenticated/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/categories': {
      id: '/authenticated/categories'
      path: '/categories'
      fullPath: '/authenticated/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/dashboard': {
      id: '/authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/authenticated/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/exports': {
      id: '/authenticated/exports'
      path: '/exports'
      fullPath: '/authenticated/exports'
      preLoaderRoute: typeof AuthenticatedExportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/reports': {
      id: '/authenticated/reports'
      path: '/reports'
      fullPath: '/authenticated/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/rules': {
      id: '/authenticated/rules'
      path: '/rules'
      fullPath: '/authenticated/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/settings': {
      id: '/authenticated/settings'
      path: '/settings'
      fullPath: '/authenticated/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/statements': {
      id: '/authenticated/statements'
      path: '/statements'
      fullPath: '/authenticated/statements'
      preLoaderRoute: typeof AuthenticatedStatementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/templates': {
      id: '/authenticated/templates'
      path: '/templates'
      fullPath: '/authenticated/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/transactions': {
      id: '/authenticated/transactions'
      path: '/transactions'
      fullPath: '/authenticated/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportsRoute: typeof AuthenticatedExportsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatementsRoute: typeof AuthenticatedStatementsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportsRoute: AuthenticatedExportsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatementsRoute: AuthenticatedStatementsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
